name: Python build

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install virtualenv
        run: |
          sudo apt update
          sudo apt install python3-pip
          python -m pip install virtualenv

      - name: Cache Python virtual environment
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-pip-cache-v1-${{ hashFiles('./requirements*.txt') }}

      - name: Install Python requirements
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          virtualenv ./.venv
          source ./.venv/bin/activate
          pip install -r ./requirements.txt -r ./requirements-code-style.txt


  code-style:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Python virtual environment
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-pip-cache-v1-${{ hashFiles('./requirements*.txt') }}

      - name: Run python static code analyzers
        run: |
          source ./.venv/bin/activate
          flake8 . --count --statistics --config ./.flake8
